@startuml Project

    left to right direction
    !theme amiga

    : Usuario(cliente): as C1

    (Pesquisar por uma CD Key) as CU001
    (Exibir uma lista de CD Keys) as CU002
    (Selecionar uma CD Key para visualizar) as CU003
    (Exibir informações detalhadas sobre o CD Key) as CU004
    (Adicionar uma ou mais CD Keys no carrinho) as CU005
    (Atualizar o carrinho com os produtos selecionados) as CU006
    (Visualizar o conteudo do carrinho) as CU007
    (Remover itens do carrinho ou ajustar a quantidade) as CU008
    (Atualizar o carrinho conforme as ações do usuário) as CU009
    (Proseguir para efetuar a compra dos itens no carrinho) as CU010
    (Solicitar as informações de pagamento e envio) as CU011
    (Processar o pagamento e gerar as CD Keys para o usuário) as CU012
    (Acessar seu histórico de compras anteriores) as CU013
    (Exibir uma lista de todas as compras do usuário) as CU014
    (Acessar e editar as informações de sua conta) as CU015
    (Modificar suas preferências de comunicação) as CU016

    C1 -- CU001
    C1 -- CU003
    C1 -- CU005
    C1 -- CU007
    C1 -- CU008
    C1 -- CU010
    C1 -- CU013
    C1 -- CU015
    C1 -- CU016
    
    CU002 ..> CU001 : <<extend>>
    CU002 <.. CU003 : <<extend>>
    CU003 <.. CU004 : <<extend>>
    CU003 ..> CU005 : <<include>>
    CU005 <.. CU006 : <<extend>>
    CU007 <.. CU005 : <<include>>
    CU007 ..> CU008 : <<include>>
    CU009 <.. CU008 : <<include>>
    CU010 <.. CU009 : <<include>>
    CU011 <.. CU010 : <<include>>
    CU012 <.. CU011 : <<include>>
    CU014 <.. CU013 : <<include>>

@enduml
